//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToDB.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqToDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; must be an interface. 的本地化字符串。
        /// </summary>
        public static string AbstractClassBuilder_TypeIsNotAnInterface {
            get {
                return ResourceManager.GetString("AbstractClassBuilder_TypeIsNotAnInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not figure out the target method for the method &apos;{0}.{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string AsyncAspectBuilder_NoTargetMethod {
            get {
                return ResourceManager.GetString("AsyncAspectBuilder_NoTargetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter &apos;cacheAspectType&apos; must be of CacheAspect type 的本地化字符串。
        /// </summary>
        public static string CacheAttribute_ParentTypeConstraintViolated {
            get {
                return ResourceManager.GetString("CacheAttribute_ParentTypeConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cast from {0} to {1} 的本地化字符串。
        /// </summary>
        public static string Convert_InvalidCast {
            get {
                return ResourceManager.GetString("Convert_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index has more then one field for the method &apos;{0}.{1}&apos;. Use CompoundValue as the Key type 的本地化字符串。
        /// </summary>
        public static string DataAccessor_IndexIsComplex {
            get {
                return ResourceManager.GetString("DataAccessor_IndexIsComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key type for the method &apos;{0}.{1}&apos; can be of type object or CompoundValue. 的本地化字符串。
        /// </summary>
        public static string DataAccessor_InvalidKeyType {
            get {
                return ResourceManager.GetString("DataAccessor_InvalidKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index is not defined for the method &apos;{0}.{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string DataAccessor_UnknownIndex {
            get {
                return ResourceManager.GetString("DataAccessor_UnknownIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DbManager object is not provided. 的本地化字符串。
        /// </summary>
        public static string DataAccessorBase_NoDbManager {
            get {
                return ResourceManager.GetString("DataAccessorBase_NoDbManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key type for the method &apos;{0}.{1}&apos; can be of type object, CompoundValue, or a scalar type. 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_BadKeyType {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_BadKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not determine object type for the method &apos;{0}.{1}&apos; 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_BadListItemType {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_BadListItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create an instance of the type &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_CantCreateTypeInstance {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_CantCreateTypeInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecuteNonQuery does not support the Destination attribute 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_CantExecuteNonQueryToDestination {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_CantExecuteNonQueryToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataSetTable attribute for method &apos;{0}.{1}&apos; may not be an index 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_DataSetTableMustBeByName {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_DataSetTableMustBeByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not have &apos;Equals&apos; method 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_EqualsMethodIsNotPublic {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_EqualsMethodIsNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The return type &apos;{0}&apos; of the method &apos;{1}&apos; is incompatible with the destination parameter type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_IncompatibleDestinationType {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_IncompatibleDestinationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecuteScalar destination must be an out or a ref parameter. 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_ScalarDestinationIsNotByRef {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_ScalarDestinationIsNotByRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scalar field name is not defined for the method &apos;{0}.{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilder_ScalarFieldNameMissing {
            get {
                return ResourceManager.GetString("DataAccessorBuilder_ScalarFieldNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More then one parameter is marked as destination 的本地化字符串。
        /// </summary>
        public static string DataAccessorBuilderTooManyDestinations {
            get {
                return ResourceManager.GetString("DataAccessorBuilderTooManyDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No such parameter: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string DataAccessot_ParameterNotFound {
            get {
                return ResourceManager.GetString("DataAccessot_ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataSet must be initialized before calling Update routine. Cannot update database from a null dataset. 的本地化字符串。
        /// </summary>
        public static string DbManager_CannotUpdateNullDataset {
            get {
                return ResourceManager.GetString("DbManager_CannotUpdateNullDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataTable must be initialized before calling Update routine. Cannot update database from a null data table. 的本地化字符串。
        /// </summary>
        public static string DbManager_CannotUpdateNullDataTable {
            get {
                return ResourceManager.GetString("DbManager_CannotUpdateNullDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection does not match the data provider type. 的本地化字符串。
        /// </summary>
        public static string DbManager_ConnectionTypeMismatch {
            get {
                return ResourceManager.GetString("DbManager_ConnectionTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dataProvider.ConnectionType must be a valid connection type 的本地化字符串。
        /// </summary>
        public static string DbManager_InvalidDataProviderConnectionType {
            get {
                return ResourceManager.GetString("DbManager_InvalidDataProviderConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dataProvider.Name must be a valid string 的本地化字符串。
        /// </summary>
        public static string DbManager_InvalidDataProviderName {
            get {
                return ResourceManager.GetString("DbManager_InvalidDataProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dataProvider.ProviderName must be a valid string 的本地化字符串。
        /// </summary>
        public static string DbManager_InvalidDataProviderProviderName {
            get {
                return ResourceManager.GetString("DbManager_InvalidDataProviderProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 providerName must be a valid string 的本地化字符串。
        /// </summary>
        public static string DbManager_InvalidProviderName {
            get {
                return ResourceManager.GetString("DbManager_InvalidProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter count does not match Parameter Value count. 的本地化字符串。
        /// </summary>
        public static string DbManager_MismatchParameterCount {
            get {
                return ResourceManager.GetString("DbManager_MismatchParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both `{0}&apos; and `{1}&apos; data providers are default 的本地化字符串。
        /// </summary>
        public static string DbManager_MoreThenOneDefaultProvider {
            get {
                return ResourceManager.GetString("DbManager_MoreThenOneDefaultProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only objects of type IDbDataParameter or arrays of IDbDataParameter are supported 的本地化字符串。
        /// </summary>
        public static string DbManager_NotDbDataParameter {
            get {
                return ResourceManager.GetString("DbManager_NotDbDataParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; key does not exist in the configuration file. 的本地化字符串。
        /// </summary>
        public static string DbManager_UnknownConfiguration {
            get {
                return ResourceManager.GetString("DbManager_UnknownConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; type of the connection could not be recognized. 的本地化字符串。
        /// </summary>
        public static string DbManager_UnknownConnectionType {
            get {
                return ResourceManager.GetString("DbManager_UnknownConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A suitable data provider is not available for configuration &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string DbManager_UnknownDataProvider {
            get {
                return ResourceManager.GetString("DbManager_UnknownDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The interface must be public. 的本地化字符串。
        /// </summary>
        public static string DuckTyping_InterfaceMustBePublic {
            get {
                return ResourceManager.GetString("DuckTyping_InterfaceMustBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;interfaceType&apos; must be an interface. 的本地化字符串。
        /// </summary>
        public static string DuckTyping_InterfaceTypeMustBeAnInterface {
            get {
                return ResourceManager.GetString("DuckTyping_InterfaceTypeMustBeAnInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number of &apos;baseObjectTypes&apos; or &apos;objs&apos;. 的本地化字符串。
        /// </summary>
        public static string DuckTyping_InvalidNumberOfObjs {
            get {
                return ResourceManager.GetString("DuckTyping_InvalidNumberOfObjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a subtype of &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string DuckTyping_NotASubtypeOf {
            get {
                return ResourceManager.GetString("DuckTyping_NotASubtypeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to query type &apos;{0}&apos; for method &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string EmitHelper_NoSuchMethod {
            get {
                return ResourceManager.GetString("EmitHelper_NoSuchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not expected. 的本地化字符串。
        /// </summary>
        public static string EmitHelper_NotExpectedType {
            get {
                return ResourceManager.GetString("EmitHelper_NotExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MethodInfo can not be changed. 的本地化字符串。
        /// </summary>
        public static string InterceptCallInfo_CallMethodInfoIsNotMutable {
            get {
                return ResourceManager.GetString("InterceptCallInfo_CallMethodInfoIsNotMutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; does not contain field &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string MapIndex_BadField {
            get {
                return ResourceManager.GetString("MapIndex_BadField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one field name or index must be specified 的本地化字符串。
        /// </summary>
        public static string MapIndex_EmptyFields {
            get {
                return ResourceManager.GetString("MapIndex_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one field index must be specified 的本地化字符串。
        /// </summary>
        public static string MapIndex_EmptyIndices {
            get {
                return ResourceManager.GetString("MapIndex_EmptyIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one field name must be specified 的本地化字符串。
        /// </summary>
        public static string MapIndex_EmptyNames {
            get {
                return ResourceManager.GetString("MapIndex_EmptyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not convert array of type &apos;{0}&apos; to array of &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string MappingSchema_IncompatibleArrayTypes {
            get {
                return ResourceManager.GetString("MappingSchema_IncompatibleArrayTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index parameter must be greater or equal to zero. 的本地化字符串。
        /// </summary>
        public static string NameOrIndexParameter_BadIndex {
            get {
                return ResourceManager.GetString("NameOrIndexParameter_BadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name must be a valid string. 的本地化字符串。
        /// </summary>
        public static string NameOrIndexParameter_BadName {
            get {
                return ResourceManager.GetString("NameOrIndexParameter_BadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not figure out the overloaded method for the method &apos;{0}.{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string OverloadAspectBuilder_NoOverloadedMethod {
            get {
                return ResourceManager.GetString("OverloadAspectBuilder_NoOverloadedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; type does not have appropriate getter. See &apos;{1}&apos; member &apos;{2}&apos; of &apos;{3}&apos; type. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_CannotGetGetter {
            get {
                return ResourceManager.GetString("TypeBuilder_CannotGetGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; type does not have appropriate setter. See &apos;{1}&apos; member &apos;{2}&apos; of &apos;{3}&apos; type. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_CannotGetSetter {
            get {
                return ResourceManager.GetString("TypeBuilder_CannotGetSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not build the &apos;{0}&apos; property of the &apos;{1}&apos; type: generic type &apos;{2}&apos; and it&apos;s generic parameter types should have only one parameter type. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_GenericShouldBeSingleTyped {
            get {
                return ResourceManager.GetString("TypeBuilder_GenericShouldBeSingleTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not build the &apos;{0}&apos; type: default constructor not found. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_NoDefaultCtor {
            get {
                return ResourceManager.GetString("TypeBuilder_NoDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not build the &apos;{0}&apos; property of the &apos;{1}&apos; type: type &apos;{2}&apos; has to have constructor taking type &apos;{3}&apos;. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_PropertyTypeHasNoCtorWithParamType {
            get {
                return ResourceManager.GetString("TypeBuilder_PropertyTypeHasNoCtorWithParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not build the &apos;{0}&apos; property of the &apos;{1}&apos; type: type &apos;{2}&apos; has to have public constructor. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_PropertyTypeHasNoPublicCtor {
            get {
                return ResourceManager.GetString("TypeBuilder_PropertyTypeHasNoPublicCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not build the &apos;{0}&apos; property of the &apos;{1}&apos; type: type &apos;{2}&apos; has to have public default constructor. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_PropertyTypeHasNoPublicDefaultCtor {
            get {
                return ResourceManager.GetString("TypeBuilder_PropertyTypeHasNoPublicDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; must implement required public method &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_PublicMethodMustBeImplemented {
            get {
                return ResourceManager.GetString("TypeBuilder_PublicMethodMustBeImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; does not implement public method &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_PublicMethodNotImplemented {
            get {
                return ResourceManager.GetString("TypeBuilder_PublicMethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method &apos;{0}&apos; of &apos;{1}&apos; has parameter &apos;{2}&apos; wich can&apos;t be handled. Please specify attrbutes [Parent] or [PropertyInfo] to get access to them. 的本地化字符串。
        /// </summary>
        public static string TypeBuilder_UnknownParameterType {
            get {
                return ResourceManager.GetString("TypeBuilder_UnknownParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not build the &apos;{0}&apos; type. 的本地化字符串。
        /// </summary>
        public static string TypeFactory_BuildFailed {
            get {
                return ResourceManager.GetString("TypeFactory_BuildFailed", resourceCulture);
            }
        }
    }
}
