//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : RMESDEV
	/// Data Source    : chenl-pc
	/// Server Version : 11.1.0.6.0
	/// </summary>
	public partial class RMESDEVDB : LinqToDB.Data.DataConnection
	{
		public ITable<SYSACTION>         SYSACTION         { get { return this.GetTable<SYSACTION>(); } }
		public ITable<SYSDEPARTMENT>     SYSDEPARTMENT     { get { return this.GetTable<SYSDEPARTMENT>(); } }
		public ITable<SYSMENU>           SYSMENU           { get { return this.GetTable<SYSMENU>(); } }
		public ITable<SYSPARAMCONFIG>    SYSPARAMCONFIG    { get { return this.GetTable<SYSPARAMCONFIG>(); } }
		public ITable<SYSROLE>           SYSROLE           { get { return this.GetTable<SYSROLE>(); } }
		public ITable<SYSROLEACTION>     SYSROLEACTION     { get { return this.GetTable<SYSROLEACTION>(); } }
		public ITable<SYSROLEMEMBER>     SYSROLEMEMBER     { get { return this.GetTable<SYSROLEMEMBER>(); } }
		public ITable<SYSROLEMENU>       SYSROLEMENU       { get { return this.GetTable<SYSROLEMENU>(); } }
		public ITable<SYSSETTING>        SYSSETTING        { get { return this.GetTable<SYSSETTING>(); } }
		public ITable<SYSSIGINLOG>       SYSSIGINLOG       { get { return this.GetTable<SYSSIGINLOG>(); } }
		public ITable<SYSUSER>           SYSUSER           { get { return this.GetTable<SYSUSER>(); } }
		public ITable<SYSUSERDEPARTMENT> SYSUSERDEPARTMENT { get { return this.GetTable<SYSUSERDEPARTMENT>(); } }
		public ITable<SYSUSERROLE>       SYSUSERROLE       { get { return this.GetTable<SYSUSERROLE>(); } }

		public RMESDEVDB()
		{
			InitDataContext();
		}

		public RMESDEVDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table(Schema="MVC", Name="SYS_ACTION")]
	public partial class SYSACTION
	{
		[Column("ACTION_ID"),        PrimaryKey,  NotNull] public string ACTIONID        { get; set; } // NVARCHAR2(40)
		[Column("MENU_ID"),             Nullable         ] public string MENUID          { get; set; } // NVARCHAR2(40)
		[Column("ACTION_NAME"),         Nullable         ] public string ACTIONNAME      { get; set; } // NVARCHAR2(100)
		[Column("ACTION_URL"),          Nullable         ] public string ACTIONURL       { get; set; } // NVARCHAR2(400)
		[Column("ACTION_ICONCLASS"),    Nullable         ] public string ACTIONICONCLASS { get; set; } // NVARCHAR2(100)
		[Column("ACTION_ICONURL"),      Nullable         ] public string ACTIONICONURL   { get; set; } // NVARCHAR2(300)
		[Column("ACTION_BID"),          Nullable         ] public string ACTIONBID       { get; set; } // NVARCHAR2(100)
	}

	[Table(Schema="MVC", Name="SYS_DEPARTMENT")]
	public partial class SYSDEPARTMENT
	{
		[Column("DEPARTMENT_ID"),   PrimaryKey,  NotNull] public string DEPARTMENTID   { get; set; } // NVARCHAR2(100)
		[Column("DEPARTMENT_NAME"),    Nullable         ] public string DEPARTMENTNAME { get; set; } // NVARCHAR2(100)
		[Column("DEPARTMENT_PID"),     Nullable         ] public string DEPARTMENTPID  { get; set; } // NVARCHAR2(100)
	}

	[Table(Schema="MVC", Name="SYS_MENU")]
	public partial class SYSMENU
	{
		[Column("MENU_ID"),        PrimaryKey,  NotNull] public string    MENUID        { get; set; } // NVARCHAR2(100)
		[Column("MENU_PID"),          Nullable         ] public string    MENUPID       { get; set; } // NVARCHAR2(100)
		[Column("MENU_URL"),          Nullable         ] public string    MENUURL       { get; set; } // NVARCHAR2(100)
		[Column("MENU_NAME"),         Nullable         ] public string    MENUNAME      { get; set; } // NVARCHAR2(100)
		[Column("MENU_ICONURL"),      Nullable         ] public string    MENUICONURL   { get; set; } // NVARCHAR2(300)
		[Column("MENU_ICONCLASS"),    Nullable         ] public string    MENUICONCLASS { get; set; } // NVARCHAR2(100)
		[Column("MENU_SEQ"),                    NotNull] public long      MENUSEQ       { get; set; } // NUMBER (11,0)
		[Column("IS_ENABLE"),         Nullable         ] public short?    ISENABLE      { get; set; } // NUMBER (4,0)
		[Column("DATE_CREATE"),       Nullable         ] public DateTime? DATECREATE    { get; set; } // DATE
	}

	[Table(Schema="MVC", Name="SYS_PARAMCONFIG")]
	public partial class SYSPARAMCONFIG
	{
		[Column, NotNull    ] public long   ID        { get; set; } // NUMBER (11,0)
		[Column,    Nullable] public string SPNAME    { get; set; } // NVARCHAR2(100)
		[Column,    Nullable] public string ARGNAME   { get; set; } // NVARCHAR2(100)
		[Column,    Nullable] public string DATATYPE  { get; set; } // NVARCHAR2(100)
		[Column,    Nullable] public string DIRECTION { get; set; } // NVARCHAR2(100)
		[Column,    Nullable] public long?  SEQ       { get; set; } // NUMBER (11,0)
	}

	[Table(Schema="MVC", Name="SYS_ROLE")]
	public partial class SYSROLE
	{
		[Column("ROLE_ID"),   PrimaryKey,  NotNull] public string ROLEID   { get; set; } // NVARCHAR2(40)
		[Column("ROLE_NAME"),    Nullable         ] public string ROLENAME { get; set; } // NVARCHAR2(100)
		[Column("ROLE_DESC"),    Nullable         ] public string ROLEDESC { get; set; } // NVARCHAR2(400)
		[Column(),               Nullable         ] public string CREATOR  { get; set; } // NVARCHAR2(100)
	}

	[Table(Schema="MVC", Name="SYS_ROLE_ACTION")]
	public partial class SYSROLEACTION
	{
		[Column("ROLE_ID"),   PrimaryKey(1), NotNull] public string ROLEID   { get; set; } // NVARCHAR2(40)
		[Column("ACTION_ID"), PrimaryKey(2), NotNull] public string ACTIONID { get; set; } // NVARCHAR2(40)
	}

	[Table(Schema="MVC", Name="SYS_ROLE_MEMBER")]
	public partial class SYSROLEMEMBER
	{
		[Column("ROLE_ID"),  NotNull    ] public string ROLEID  { get; set; } // NVARCHAR2(100)
		[Column("ROLE_PID"), NotNull    ] public string ROLEPID { get; set; } // NVARCHAR2(100)
		[Column(),              Nullable] public string CREATOR { get; set; } // NVARCHAR2(100)
	}

	[Table(Schema="MVC", Name="SYS_ROLE_MENU")]
	public partial class SYSROLEMENU
	{
		[Column("MENU_ID"), PrimaryKey(1), NotNull] public string MENUID { get; set; } // NVARCHAR2(40)
		[Column("ROLE_ID"), PrimaryKey(2), NotNull] public string ROLEID { get; set; } // NVARCHAR2(100)
	}

	[Table(Schema="MVC", Name="SYS_SETTING")]
	public partial class SYSSETTING
	{
		[PrimaryKey, NotNull    ] public long   ID    { get; set; } // NUMBER (11,0)
		[Column,        Nullable] public string CODE  { get; set; } // NVARCHAR2(100)
		[Column,        Nullable] public string VALUE { get; set; } // NVARCHAR2(240)
	}

	[Table(Schema="MVC", Name="SYS_SIGIN_LOG")]
	public partial class SYSSIGINLOG
	{
		[Column("LINE_ID"),       PrimaryKey,  NotNull] public long      LINEID       { get; set; } // NUMBER (11,0)
		[Column("LOCAL_IP"),         Nullable         ] public string    LOCALIP      { get; set; } // NVARCHAR2(100)
		[Column("NET_IP"),           Nullable         ] public string    NETIP        { get; set; } // NVARCHAR2(100)
		[Column("USER_ID"),          Nullable         ] public string    USERID       { get; set; } // NVARCHAR2(100)
		[Column("USER_NAME"),        Nullable         ] public string    USERNAME     { get; set; } // NVARCHAR2(100)
		[Column("LOGIN_ADDRESS"),    Nullable         ] public string    LOGINADDRESS { get; set; } // NVARCHAR2(400)
		[Column("LOGIN_DATE"),       Nullable         ] public DateTime? LOGINDATE    { get; set; } // DATE
	}

	[Table(Schema="MVC", Name="SYS_USER")]
	public partial class SYSUSER
	{
		[Column("USER_ID"),        PrimaryKey,  NotNull] public string    USERID        { get; set; } // NVARCHAR2(60)
		[Column("USER_NAME"),         Nullable         ] public string    USERNAME      { get; set; } // NVARCHAR2(100)
		[Column("USER_PWD"),          Nullable         ] public string    USERPWD       { get; set; } // NVARCHAR2(100)
		[Column("USER_EMAIL"),        Nullable         ] public string    USEREMAIL     { get; set; } // NVARCHAR2(100)
		[Column("USER_MOBILE"),       Nullable         ] public string    USERMOBILE    { get; set; } // NVARCHAR2(100)
		[Column("IS_ENABLE"),         Nullable         ] public sbyte?    ISENABLE      { get; set; } // NUMBER (1,0)
		[Column("IS_ADMIN"),          Nullable         ] public sbyte?    ISADMIN       { get; set; } // NUMBER (1,0)
		[Column("DATE_LOGINLAST"),    Nullable         ] public DateTime? DATELOGINLAST { get; set; } // DATE
		[Column("JSON_CONFIG"),       Nullable         ] public string    JSONCONFIG    { get; set; } // NVARCHAR2(400)
		[Column("USER_SEX"),          Nullable         ] public string    USERSEX       { get; set; } // NVARCHAR2(20)
		[Column("USER_ADDRESS"),      Nullable         ] public string    USERADDRESS   { get; set; } // NVARCHAR2(400)
		[Column("CREATER_ID"),        Nullable         ] public string    CREATERID     { get; set; } // NVARCHAR2(60)
	}

	[Table(Schema="MVC", Name="SYS_USER_DEPARTMENT")]
	public partial class SYSUSERDEPARTMENT
	{
		[Column("USER_ID"),       PrimaryKey(1), NotNull] public string USERID       { get; set; } // NVARCHAR2(100)
		[Column("DEPARTMENT_ID"), PrimaryKey(2), NotNull] public string DEPARTMENTID { get; set; } // NVARCHAR2(100)
	}

	[Table(Schema="MVC", Name="SYS_USER_ROLE")]
	public partial class SYSUSERROLE
	{
		[Column("USER_ID"), PrimaryKey(1), NotNull] public string USERID { get; set; } // NVARCHAR2(100)
		[Column("ROLE_ID"), PrimaryKey(2), NotNull] public string ROLEID { get; set; } // NVARCHAR2(40)
	}

	public static partial class TableExtensions
	{
		public static SYSACTION Find(this ITable<SYSACTION> table, string ACTIONID)
		{
			return table.FirstOrDefault(t =>
				t.ACTIONID == ACTIONID);
		}

		public static SYSDEPARTMENT Find(this ITable<SYSDEPARTMENT> table, string DEPARTMENTID)
		{
			return table.FirstOrDefault(t =>
				t.DEPARTMENTID == DEPARTMENTID);
		}

		public static SYSMENU Find(this ITable<SYSMENU> table, string MENUID)
		{
			return table.FirstOrDefault(t =>
				t.MENUID == MENUID);
		}

		public static SYSROLE Find(this ITable<SYSROLE> table, string ROLEID)
		{
			return table.FirstOrDefault(t =>
				t.ROLEID == ROLEID);
		}

		public static SYSROLEACTION Find(this ITable<SYSROLEACTION> table, string ROLEID, string ACTIONID)
		{
			return table.FirstOrDefault(t =>
				t.ROLEID   == ROLEID &&
				t.ACTIONID == ACTIONID);
		}

		public static SYSROLEMENU Find(this ITable<SYSROLEMENU> table, string MENUID, string ROLEID)
		{
			return table.FirstOrDefault(t =>
				t.MENUID == MENUID &&
				t.ROLEID == ROLEID);
		}

		public static SYSSETTING Find(this ITable<SYSSETTING> table, long ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static SYSSIGINLOG Find(this ITable<SYSSIGINLOG> table, long LINEID)
		{
			return table.FirstOrDefault(t =>
				t.LINEID == LINEID);
		}

		public static SYSUSER Find(this ITable<SYSUSER> table, string USERID)
		{
			return table.FirstOrDefault(t =>
				t.USERID == USERID);
		}

		public static SYSUSERDEPARTMENT Find(this ITable<SYSUSERDEPARTMENT> table, string USERID, string DEPARTMENTID)
		{
			return table.FirstOrDefault(t =>
				t.USERID       == USERID &&
				t.DEPARTMENTID == DEPARTMENTID);
		}

		public static SYSUSERROLE Find(this ITable<SYSUSERROLE> table, string USERID, string ROLEID)
		{
			return table.FirstOrDefault(t =>
				t.USERID == USERID &&
				t.ROLEID == ROLEID);
		}
	}
}
